networks:
    school-grades-sec:
        driver: bridge

volumes:
    school-grades-sec:

services:
    database:
        image: postgres:latest
        hostname: db
        container_name: postgres-school-grades-sec
        networks:
            - school-grades-sec
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: school_grades_data
        volumes:
            - school-grades-sec:/var/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s

    app:
        build: .
        image: school-grades-sec:2.0
        container_name: app-school-grades-sec
        networks:
            - school-grades-sec
        environment:
            DB_HOST: db
        ports:
            - 8080:8080
        depends_on:
            database:
                condition: service_healthy
